version: '2.1'

volumes:
  volume_pihole:
  volume_dnsmasq:

services:
  pihole:
    build:
        context: ./
    volumes:
       - volume_pihole:/etc/pihole/
       - volume_dnsmasq:/etc/dnsmasq.d/
    privileged: true
    #ports:
    #  - "53:53/tcp"
    #  - "53:53/udp"
    #  - "67:67/udp"
    #  - "80:80/tcp"
    #  - "443:443/tcp"
    environment:
      TZ: 'Europe/Luxembourg'
      WEBPASSWORD: 'admin'
      WEB_PORT: 8089
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    network_mode: host
