FROM pihole/pihole:4.3.1-4_armhf
#FROM pihole/pihole:4.3.1-4_arm64

# Fixes required to run on balenaOS
RUN sed -i '/$AUTHORIZED_HOSTNAMES = array(/ a "balena-devices.com",' /var/www/html/admin/scripts/pi-hole/php/auth.php
RUN echo "bind-interfaces" >> /etc/dnsmasq.conf
